Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -15,7 +15,10 @@ runs:
       run: IFS=',' read -r -a PROFILES <<< "${{inputs.profiles}}"
       shell: bash
     - name: 'Check files for availability'
-      run: for f in ${PROFILES[@]}; do [ -f "${{inputs.old_dir}}/oas_$f.json" -o -f "${{inputs.new_dir}}/oas_$f.json" ] && : || ( echo "Cannot find any specification of profile $f"; exit 1 ); done
+      run: for f in ${PROFILES[@]}; do [ -f "$OLD_DIR/oas_$f.json" -o -f "$NEW_DIR/oas_$f.json" ] && : || ( echo "Cannot find any specification of profile $f"; exit 1 ); done
       shell: bash
+      env:
+        - OLD_DIR: ${{inputs.old_dir}}
+        - NEW_DIR: ${{inputs.new_dir}}
     - run: docker run openapitools/openapi-diff:latest 
       shell: bash
