Change behavior when breaking changes occur
When breaking changes occur, the diff files will be uploaded and the pipeline fails

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -57,19 +57,20 @@ runs:
             fi
         done
         
-        set -e 
-        
-        if [ $STATUS -ge 1 ]; then 
-            echo "::error::Breaking changes detected"
-            exit 1
-        fi
+        set -e
       shell: bash
       env:
         OLD_DIR: ${{inputs.old_dir}}
         NEW_DIR: ${{inputs.new_dir}}
-    
     - name: 'Upload specifications'
       uses: actions/upload-artifact@v4
       with:
         name: 'OpenAPI differences'
         path: oas_diff/*.html
+    - name: 'Check breaking info'
+      shell: bash
+      run: |
+        if [ $STATUS -ge 1 ]; then 
+          echo "::error::Breaking changes detected"
+          exit 1
+        fi
